  language: python
  python:
    - "3.6"
  install:
    - pip install tox
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source ~/.poetry/env

  script:
    -  tox
