[tool.poetry]
name = "dagpy"
version = "0.1.1"
description = "Thin python wrapper around dagre-d3"
authors = []

[tool.poetry.dependencies]
python = "~3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
mypy = "^0.701"
